ryanve/aaronirwin.com

- performances.md
> Late update

- README.md
> describe editing steps

- performances.md
> Updated performances

- performances.md
> another gig

- performances.md
> November 1

- README.md
```
[Bandcamp](https://aaronirwin.bandcamp.com)
```
[Bandcamp](https://aaronirwin.bandcamp.com)
> Put markdown link example in readme

- _config.yml
`sitemap.xml` should help with SEO making pages more findable in Google
`sitemap.xml` is a web standard for listing website pages
It'll create and update on https://aaronirwin.com/sitemap.xml
> Automagically create sitemap.xml

- _config.yml
Reorder these to higher in file because neither seem to work rn
> Move plugins higher up

- index.html
[Examples show without quotes](https://github.com/jekyll/jekyll-redirect-from)
> Remove redirect_from quotes

- _albums/music-for-sextet.md
create [new album page](https://aaronirwin.com/albums/music-for-sextet/) using images from #104 and deets from aaron
> create music for sextet page

- index.html
link [homepage](https://aaronirwin.com) to [album page](https://aaronirwin.com/albums/music-for-sextet/) #105
> drop new album onto homepage

- _config.yml
try setting title in config because title on homepage is showing up empty
> define title in config

- _albums/music-for-sextet.md
move into the list with the other deets
> move special thank you

- _config.yml
> move title to defaults

- _albums/music-for-sextet.md
> Spell Blackburn

- _albums/music-for-sextet.md
Add streaming links to the [album page](https://aaronirwin.com/albums/music-for-sextet/)
> **Available on [Innova](https://www.innova.mu/albums/aaron-irwin/music-sextet), [Apple](https://music.apple.com/us/album/music-for-sextet/1547274920), [Spotify](https://open.spotify.com/album/12u781WyobHqFPWpLc8aTR)**
> Available wwworldwide

- performances.md
> ## [2023](https://aaronirwin.com/performances/#2023)
- Aaron Irwin's Wobegon Trio - June 20th - IBeam - Brooklyn, NY 
- Aaron Irwin's Wobegon Trio - June 21st - Music Land - Bel Air, MD 
- Aaron Irwin's Wobegon Trio - June 23rd - Barking Legs Theater
- Aaron Irwin's Wobegon Trio - June 24th - East Village Arts - Birmingham, AL
- Aaron Irwin's Wobegon Trio - June 25th - [Petra's](https://www.eventbrite.com/e/wobegon-with-ghost-trees-tickets-630992404267) - Charlotte, NC
- Aaron Irwin's Wobegon Trio - June 26th - Red Light Cafe - Atlanta, GA
- Aaron Irwin's Wobegon Trio - June 28th - [North Street Cabaret](https://www.northstreetcabaret.com/events/2023/6/28/aaron-erwin-trio-wobegon) - Madison, WI
- Aaron Irwin's Wobegon Trio - July 1 - Icehouse - Minneapolis, MD 
- Aaron Irwin's Wobegon …
> ((( 2023 ))) performances )))

- _albums/after.md
https://aaronirwin.com/albums/after
> (after) album page

- _albums/after.md
> theze imagez

- index.html
> (after) homepage

- _albums/after.md
> img sourcery

- albums.md
- css/theme.css
this way maintains the column gap even when one column
> compose grid gap repeat

- bio.md
- media.md
> refresh images
